version: '3.8'

services:
  fastapi-rag:
    build: .
    image: 'fastapi-rag'
    ports:
      - '8888:8888'
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - APP_NAME=${APP_NAME}
    command: uvicorn app.main:app --host 0.0.0.0 --port 8888 --reload